# Generated by Django 6.0.3 on 2026-04-21 14:02
from pathlib import Path
from django.db import migrations
import json

def load_initial_categories(apps,schema_editor):
    Category = apps.get_model('categories','Category')
    fixture_path = Path(__file__).resolve().parent.parent / 'fixtures' / 'categories.json'

    with fixture_path.open(encoding='utf-8') as fixture_file:
        fixtures = json.load(fixture_file)

    for entry in fixtures:
        fields = entry.get('fields',{})
        name = fields.get('name')
        if name:
            Category.objects.update_or_create(name=name,defaults=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_categories,migrations.RunPython.noop),
    ]
