# Generated by Django 6.0.3 on 2026-04-21 14:08
from pathlib import Path
from django.db import migrations
import json
from django.utils.text import slugify

def load_initial_products(apps,schema_editor):
    Product= apps.get_model('products','Product')
    fixture_path = Path(__file__).resolve().parent.parent / 'fixtures' / 'products.json'

    with fixture_path.open(encoding='utf-8') as fixture_file:
        fixtures=json.load(fixture_file)

    for entry in fixtures:
        fields = entry.get('fields',{})
        name = fields.get('name')
        if name:
            # Generate slug since its now required to be unique
            slug = slugify(name)
            # Ensure slug uniqueness by appending pk if needed
            pk = entry.get('pk')
            existing = Product.objects.filter(slug=slug).exclude(name=name).first()
            if existing:
                slug = f"{slug}-{pk}"
            fields['slug'] = slug
            Product.objects.update_or_create(name=name,defaults=fields)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug'),
        ('categories','0002_load_initial_categories'),
    ]

    operations = [
        migrations.RunPython(load_initial_products,migrations.RunPython.noop),
    ]
